-- create tables

CREATE MEMORY TABLE "AFM_CALCULATOR"."BUNDLE"(
    "ID" CHARACTER VARYING(255) NOT NULL,
    "ID_PSP" CHARACTER VARYING(255),
    "MAX_PAYMENT_AMOUNT" BIGINT,
    "MIN_PAYMENT_AMOUNT" BIGINT,
    "PAYMENT_AMOUNT" BIGINT,
    "PAYMENT_METHOD" INTEGER,
    "TOUCHPOINT" INTEGER,
    "TYPE" INTEGER
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."CIBUNDLE"(
    "ID" CHARACTER VARYING(255) NOT NULL,
    "CI_FISCAL_CODE" CHARACTER VARYING(255),
    "BUNDLE_ID" CHARACTER VARYING(255)
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."CIBUNDLEATTRIBUTE"(
    "ID" CHARACTER VARYING(255) NOT NULL,
    "MAX_PAYMENT_AMOUNT" BIGINT,
    "TRANSFER_CATEGORY" CHARACTER VARYING(255),
    "TRANSFER_CATEGORY_RELATION" INTEGER
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."TRANSFERCATEGORY"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255)
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."BUNDLE_TRANSFER_CATEGORY_LIST"(
    "BUNDLE_ID" CHARACTER VARYING(255) NOT NULL,
    "TRANSFER_CATEGORY_LIST_ID" BIGINT NOT NULL
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."CIBUNDLE_ATTRIBUTES"(
    "CI_BUNDLE_ID" CHARACTER VARYING(255) NOT NULL,
    "ATTRIBUTES_ID" CHARACTER VARYING(255) NOT NULL
);