-- create tables

CREATE MEMORY TABLE "AFM_CALCULATOR"."BUNDLE" (
    "ID" CHARACTER VARYING(255) NOT NULL,
    "ID_PSP" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255),
    "DESCRIPTION" CHARACTER VARYING(255),
    "MAX_PAYMENT_AMOUNT" BIGINT,
    "MIN_PAYMENT_AMOUNT" BIGINT,
    "PAYMENT_AMOUNT" BIGINT,
    "PAYMENT_METHOD" INTEGER,
    "TOUCHPOINT" INTEGER,
    "TYPE" INTEGER
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."CIBUNDLE"(
    "ID" CHARACTER VARYING(255) NOT NULL,
    "CI_FISCAL_CODE" CHARACTER VARYING(255),
    "BUNDLE_ID" CHARACTER VARYING(255)
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."CIBUNDLEATTRIBUTE"(
    "ID" CHARACTER VARYING(255) NOT NULL,
    "MAX_PAYMENT_AMOUNT" BIGINT,
    "TRANSFER_CATEGORY" CHARACTER VARYING(255),
    "TRANSFER_CATEGORY_RELATION" INTEGER
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."TRANSFERCATEGORY"(
    "ID" BIGINT NOT NULL,
    "NAME" CHARACTER VARYING(255)
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."BUNDLE_TRANSFER_CATEGORY_LIST"(
    "BUNDLE_ID" CHARACTER VARYING(255) NOT NULL,
    "TRANSFER_CATEGORY_LIST_ID" BIGINT NOT NULL
);

CREATE MEMORY TABLE "AFM_CALCULATOR"."CIBUNDLE_ATTRIBUTES"(
    "CI_BUNDLE_ID" CHARACTER VARYING(255) NOT NULL,
    "ATTRIBUTES_ID" CHARACTER VARYING(255) NOT NULL
);

ALTER TABLE "AFM_CALCULATOR"."TRANSFERCATEGORY" ADD CONSTRAINT "AFM_CALCULATOR"."CONSTRAINT_8" PRIMARY KEY("ID");
ALTER TABLE "AFM_CALCULATOR"."CIBUNDLE_ATTRIBUTES" ADD CONSTRAINT "AFM_CALCULATOR"."UK_940TSB9VEEEMPAD3YG7CFLRA3" UNIQUE("ATTRIBUTES_ID");
ALTER TABLE "AFM_CALCULATOR"."CIBUNDLE_ATTRIBUTES" ADD CONSTRAINT "AFM_CALCULATOR"."FKILHJ272BN1CWM8K0Y16IKW9AH" FOREIGN KEY("ATTRIBUTES_ID") REFERENCES "AFM_CALCULATOR"."CIBUNDLEATTRIBUTE"("ID") NOCHECK;
ALTER TABLE "AFM_CALCULATOR"."CIBUNDLE_ATTRIBUTES" ADD CONSTRAINT "AFM_CALCULATOR"."FKENWOMUCN5HKLH0GDQP8J6YKMF" FOREIGN KEY("CI_BUNDLE_ID") REFERENCES "AFM_CALCULATOR"."CIBUNDLE"("ID") NOCHECK;
ALTER TABLE "AFM_CALCULATOR"."CIBUNDLEATTRIBUTE" ADD CONSTRAINT "AFM_CALCULATOR"."CONSTRAINT_1" PRIMARY KEY("ID");
ALTER TABLE "AFM_CALCULATOR"."CIBUNDLE" ADD CONSTRAINT "AFM_CALCULATOR"."FK5BM2TX42IPNN1U8S5G83IX33W" FOREIGN KEY("BUNDLE_ID") REFERENCES "AFM_CALCULATOR"."BUNDLE"("ID") NOCHECK;
ALTER TABLE "AFM_CALCULATOR"."CIBUNDLE" ADD CONSTRAINT "AFM_CALCULATOR"."CONSTRAINT_B" PRIMARY KEY("ID");
ALTER TABLE "AFM_CALCULATOR"."BUNDLE_TRANSFER_CATEGORY_LIST" ADD CONSTRAINT "AFM_CALCULATOR"."FKBSXIKK0A7CR5AOTFQGSR49LWG" FOREIGN KEY("TRANSFER_CATEGORY_LIST_ID") REFERENCES "AFM_CALCULATOR"."TRANSFERCATEGORY"("ID") NOCHECK;
ALTER TABLE "AFM_CALCULATOR"."BUNDLE_TRANSFER_CATEGORY_LIST" ADD CONSTRAINT "AFM_CALCULATOR"."FK2HA1XFVIBDAX2F55QHD31R0GC" FOREIGN KEY("BUNDLE_ID") REFERENCES "AFM_CALCULATOR"."BUNDLE"("ID") NOCHECK;
ALTER TABLE "AFM_CALCULATOR"."BUNDLE" ADD CONSTRAINT "AFM_CALCULATOR"."CONSTRAINT_7" PRIMARY KEY("ID");